{
 "title": "FutureX Microservices Dashboard",
 "tags": [
  "spring-boot",
  "microservices"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Solicitudes y Errores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Solicitudes por Minuto por Endpoint",
   "type": "graph",
   "description": "Número de solicitudes por minuto para cada endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Solicitudes/min" }
   ],
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{application=~\"fx-.*-service\"}[1m])) * 60",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Porcentaje de Errores (Últimas 6 horas)",
   "type": "gauge",
   "description": "Porcentaje de errores vs solicitudes exitosas en las últimas 6 horas",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_requests_seconds_count{application=~\"fx-.*-service\", status=~\"5..\"}[6h])) / sum(rate(http_server_requests_seconds_count{application=~\"fx-.*-service\"}[6h]))) * 100",
     "legendFormat": "Tasa de Error"
    }
   ]
  },
  { "title": "Uso de Recursos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Uso de CPU",
   "type": "graph",
   "description": "Uso de CPU para los servicios",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "CPU Usage" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{application=~\"fx-.*-service\"}",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Uso de Memoria Heap (%)",
   "type": "graph",
   "description": "Uso de memoria de los servicios",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percent", "label": "Memoria Usada" }
   ],
   "targets": [
    {
     "expr": "sum by (application) (jvm_memory_used_bytes{application=~\"fx-.*-service\", area=\"heap\"}) / sum by (application) (jvm_memory_max_bytes{application=~\"fx-.*-service\", area=\"heap\"}) * 100",
     "legendFormat": "{{application}}"
    }
   ]
  }
 ]
}